---
- hosts: "bootstrap-server, consul-server"
  sudo: yes

  tasks:

    - name: Referencing key
      debug:
        var: hostvars[groups['bootstrap-server'][0]]['key']['stdout_lines']

    - name: Consul Regular server configuration
      template:
        src: ../templates/server-config.j2
        dest: /etc/consul.d/server/config.json

    - name: Create Startup script Server
      template:
        src: ../templates/server-init.j2
        dest: /etc/init/consul.conf

    - name: Start consul bootstrap
      command: start consul