---
- hosts: "client"
  sudo: yes

  tasks:

    - name: Referencing key consul
      debug:
        var: hostvars[groups['bootstrap-server'][0]]['key']['stdout_lines']

    - name: Consul client configuration
      template:
        src: ../templates/client-config.j2
        dest: /etc/consul.d/client/config.json

    - name: Create Startup script for client
      template:
        src: ../templates/client-init.j2
        dest: /etc/init/consul.conf

    - name: Start consul bootstrap
      command: start consul